workflows:
  macos-release:
    name: AuraShow Mac Installer
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: ðŸ› ï¸ Setup Environment
        script: |
          # 1. Create the missing .env file (Prevents "asset not found" crash)
          echo "VAR=value" > .env

          # 2. Ensure macOS support is active
          flutter config --enable-macos
          flutter create .

      - name: ðŸ“¦ Install Dependencies
        script: |
          flutter pub get
          cd macos
          pod install
          
      - name: ðŸš€ Build macOS App
        script: |
          # Build the release version
          flutter build macos --release
          
      - name: ðŸ’¿ Create DMG Installer
        script: |
          # Install the packaging tool
          brew install create-dmg
          
          # Define paths
          APP_NAME="AuraShow"
          APP_PATH="build/macos/Build/Products/Release/$APP_NAME.app"
          DMG_PATH="$APP_NAME.dmg"
          
          # Run the packager
          create-dmg \
            --volname "$APP_NAME Installer" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --hide-extension "$APP_NAME.app" \
            --app-drop-link 600 185 \
            "$DMG_PATH" \
            "$APP_PATH"
            
    artifacts:
      - "*.dmg"
    publishing:
      email:
        recipients:
          - your_email@example.com  # <--- Verify this is still correct!