workflows:
  macos-release:
    name: 🍎 AuraShow Mac Release (M2)
    instance_type: mac_mini_m2
    max_build_duration: 60
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
    scripts:
      - name: 🔢 Set Version & Env
        script: |
          echo "ENV=production" > .env
          NEW_VERSION="1.0.$BUILD_NUMBER"
          echo "Building Version: $NEW_VERSION"
          flutter config --enable-macos
          flutter create .

      - name: 🩺 Run Analysis (Non-Blocking)
        script: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          # Run analysis but ignore errors so the build continues
          flutter analyze || true 

      - name: 📦 Install Pods
        script: |
          cd macos
          pod install
          cd ..

      - name: 🚀 Build macOS App
        script: |
          flutter build macos --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER

      - name: 🔐 Ad-Hoc Sign
        script: |
          codesign --force --deep --sign - "build/macos/Build/Products/Release/AuraShow.app"

      - name: 💿 Create DMG Installer
        script: |
          APP_NAME="AuraShow"
          BUILD_DIR="build/macos/Build/Products/Release"
          APP_PATH="$BUILD_DIR/$APP_NAME.app"
          STAGING_DIR="dmg_staging"
          DMG_NAME="$APP_NAME.dmg"

          rm -rf "$STAGING_DIR" "$DMG_NAME"
          mkdir -p "$STAGING_DIR"
          cp -r "$APP_PATH" "$STAGING_DIR/"
          ln -s /Applications "$STAGING_DIR/Applications"

          hdiutil create -volname "$APP_NAME Installer" \
                         -srcfolder "$STAGING_DIR" \
                         -ov -format UDZO \
                         "$DMG_NAME"
            
    artifacts:
      - "*.dmg"
      - "build/macos/Build/Products/Release/*.app"
    publishing:
      email:
        recipients:
          - ronald.datcher4@gmail.com