workflows:
  macos-release:
    name: AuraShow Mac Installer
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: ðŸ› ï¸ Setup Environment
        script: |
          # 1. Create dummy .env to satisfy Flutter assets
          echo "VAR=value" > .env

          # 2. Ensure macOS folders are valid
          flutter config --enable-macos
          flutter create .

      - name: ðŸ“¦ Install Dependencies
        script: |
          flutter pub get
          cd macos
          pod install
          
      - name: ðŸš€ Build macOS App
        script: |
          # Build the release version
          flutter build macos --release
          
      - name: ðŸ’¿ Create Installer (Reliable Method)
        script: |
          APP_NAME="AuraShow"
          BUILD_DIR="build/macos/Build/Products/Release"
          APP_PATH="$BUILD_DIR/$APP_NAME.app"
          STAGING_DIR="dmg_staging"
          DMG_NAME="$APP_NAME.dmg"

          # 1. Prepare a folder with the App and a link to /Applications
          mkdir -p "$STAGING_DIR"
          cp -r "$APP_PATH" "$STAGING_DIR/"
          ln -s /Applications "$STAGING_DIR/Applications"

          # 2. Create the DMG using native macOS tools (No AppleScript = No Timeouts)
          hdiutil create -volname "$APP_NAME Installer" \
                         -srcfolder "$STAGING_DIR" \
                         -ov -format UDZO \
                         "$DMG_NAME"
            
    artifacts:
      - "*.dmg"
    publishing:
      email:
        recipients:
          - your_email@example.com  # <--- Make sure this is your email!